apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-new1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-new1
  template:
    metadata:
      labels:
        app: redis-new1
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: redis-new1
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-new11
spec:
  ports:
  - port: 6379
  selector:
    app: redis-new1
